### PR TITLE
UR20 at Dumo Lab

### PR DESCRIPTION
**Pull request by atx820**
Universal Robot UR20 Robot at Dumo Lab at Upenn, Weitzman School of Design

### CODE REVIEW

**Comment by visose** [comment]
Hi @atx820, could you reduce the mesh size of the UR20 to under 10 MB? (ideally less). The library UniversalRobots.3dm was updated with a UR20 you can use, although this might be too low resolution.

**Comment by atx820** [comment]
HI visose,
Thank you for your reply! Actually I just checked the UniversalRobots
library and the resolution is ok to use! thanks for making changes.

Best,
Bowen

**Comment by visose** [comment]
Hi @atx820, could you clarify if this means you want to close this PR without merging?
You can also copy the geometry of the robot into the 3dm file of this library if you prefer to have your own separate library.

**Comment by atx820** [comment]
Yes, I am closing it now.

**Pull request closed without merging**
