### PR TITLE
Fixes "XML tag 'Tool is missing 'Tcp tag"

### PR DESCRIPTION
**Pull request by lin-ycv**
changed TCP to Tcp to match plugin tag
changed DI and DO to start from 0 so slider and SRC would be the same value

### CODE REVIEW

**Comment by visose** [comment]
Hi, are you sure about adding the "0" IOs? I think KUKAs start at 1, so the controller's first output is 1, not 0. And in the plugin, since Grasshopper is index 0 based, you would use index 0 to select the DO 1. A bit confusing, I know.

**Comment by lin-ycv** [comment]
Yes, kuka start at 1, but I don't think that's an issue, we chooses our IO setting base on what we see on the controller, so it's much more intuitive to use 27 if we see 27.
And since the controller would never show IO 0, there's no issues there.

**Comment by visose** [comment]
I could add flag on the DO component to to switch between zero based and the controller's numbering.

**Comment by visose** [comment]
I added the "useControllerNumbering" optional attribute to the IO element. This allows you to use the signal numbers directly in components like SetDO, WaitDI, etc. and ignores any IO names specified in the xml. This will work with KUKA, UR and Staubli, not with ABB, as it requires signal names.

**Pull request merged**
